"""
Copyright (C) 2022  Alexey Pavlov

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""

SPLASHES = [
    "The moon is not a planet",
    "Pluto = Planet",
    "Ayy Yep!",
    "What's my purpose?",
    "MCPI_SPEEDHACK",
    "MCPIL-Revival",
    "Minescripters",
    "I use Planet BTW",
    "Snowball",
    "Robo",
    "If I could, I would. But I can't, so I shan't.",
    "SyntaxError: invalid syntax",
    "We Fixed The Rail!",
    "The World Of Notch!",
    "github.com/mcpiscript/Planet!",
    "Now with fly-hacks!",
    "Now with custom skins!",
    "Now with *fancy icons*!",
    "@Banana",
    "BANANA!",
    'To "Na" Or Not To "Na", that is the question!',
    "Not Minecraft Java!",
    "Oh yeah, that version...",
    "Segmentation fault (core dumped)",
    "It's the Segment's Fault!",
    "Who is StevePi?",
    "(Not) Made by Notch!",
    "Open-Source!",
    "RIP all MCPILs, 2020-2022",
    "StevePi = Leha confirmed?",
    "Watch out for StevePi!",
    "Didn't remove Herobrine!",
    "Check out PBPT Anarchy!",
    "你好中国",
    "한국 안녕하세요!",
    "日本ハロー！",
    "Привет Россия!",
    "Підтримай Україну!",
    "Supercalifragilisticexpialidocious!",
    "Now with multiplayer!",
    "RED EXE ENGINEER GAMING",
    "Play Minecraft Pi Edition, watch Red-Exe-Engineer, get PIG!",
    "Wat",
    "About the same size as Earth",
    "Now with translations!",
    "Now with dynamic building!",
    "Now with more surprises!",
    "Now with more confusion!",
    "Now without pi-nbt!",
    "Now does not need gcc!",
    "Planet 2 coming soon!",
    "Leaked!",
    "Bater Wuckets are bad!",
    "Secret stuff!",
    "StevePi Org is fake?",
    "No way!",
    "You would touch with a 50 foot pole!",
    "Minecraft Pi Reborn ++ Extended 5G Ultra Plus Minus Fold Mini Max Pro Galaxy",
    "No chat reports!",
    "#saveminecraft",
    "Technoblade never dies!",
    "Gotta work!",
    "Work all day!",
    "You are AFK!",
    "Amir is a thief.",
    "Shrimpyy is a thief.",
    "Pure-Python!",
    "The newest anarchy launcher!",
    "!1!1!",
    "!!!!!",
    "Jetpacks!",
    "That's all folks! - Day 984",
    "The countdown to end all counters: 16",
    "Star Wars!",
    "Gotta fill with more splash texts!",
    "Most end with!",
    "How am I going to feed jelly those days?",
    "There is only one can of cat food left, and that's going to the market",
    "We ashk for a shmall donatshion of ten thoushand diamondshs!",
    "YOU SHPEAK WHEN SHPOKEN TO!",
    "SSHHUT UP!",
    "You were exclusively banned from the deep dark!",
    "We got the enchanter!",
    "S tier!",
    "Kraineff is a thief",
    "Top 10 Bdubs rage collection!",
    "We're gonna steal a mountain!",
    "Target: steal a mountain!",
    "Let's go steal a mountain!",
    "The first tech mod!",
    "#nochatreports",
    "But there was something SUSPICIOUS about this pool party!",
    "----END SPLASH TEXT----",
    "----BEGIN SPLASH TEXT----",
    "Love2D > Pacake",
    "FG6 had this idea first... probably...",
]
